#import <DevToolsCore/PBXGlobalID.h>
#import <DevToolsCore/PBXObject.h>
#import <DevToolsCore/PBXFileType.h>
#import <DevToolsCore/PBXBuildSettingsDictionary.h>
#import <DevToolsCore/PBXBuildFile.h>
#import <DevToolsCore/PBXBuildPhase.h>
#import <DevToolsCore/PBXContainer.h>
#import <DevToolsCore/PBXGroup.h>
#import <DevToolsCore/PBXGroupEnumerator.h>
#import <DevToolsCore/PBXProject.h>
#import <DevToolsCore/PBXReference.h>
#import <DevToolsCore/PBXTarget.h>
#import <DevToolsCore/PBXFileReference.h>
#import <DevToolsCore/XCBuildConfigurationType.h>
#import <DevToolsCore/XCBuildConfiguration.h>
#import <DevToolsCore/XCConfigurationList.h>
#import <DevToolsCore/XCPath.h>
#import <DevToolsCore/XCFileSystemNode.h>
#import <DevToolsCore/XCFileSystemVNode.h>
#import <DevToolsCore/XCSpecification.h>